app/app.py
from flask import Flask
from appdb import db
from routes.main_routes import main


app = Flask(__name__)
app.config.from_object("config.Config")

#INitialize DB
db.init_app(app)

#Register routes
app.register_blueprint(main)

if __name__ == '__main__':
    app.run(debug=True)

app/routes/main_routes.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template("index.html")

@main.route("/about")
def about():
    return render_template("about.html")

app/templates/about.html
<h1> This is an about page
</h1>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlaskDB</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: #f4f6f9;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        header {
            background: #007bff;
            color: white;
            padding: 15px 0;
            font-size: 1.5rem;
        }
        main {
            padding: 40px;
        }
        a {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 20px;
            background: #007bff;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            transition: 0.3s;
        }
        a:hover {
            background: #0056b3;
        }
    </style>
</head>
<body>
    <header>
        FlaskDB
    </header>
    <main>
        <h1>Welcome</h1>
        <a href="{{ url_for('main.about') }}">About</a>
    </main>
</body>
</html>